### ISSUE TITLE
Clarify that "No branch selected by default" is the expected behavior

### ISSUE THREAD

**Issue by fberat** [fedora-copr/copr#2528]
It is unclear to me whether this behavior is expected or not.

When starting a new build through distgit, COPR doesn't select the branch corresponding to the chroot that is built on.

Example: if you have a fedora-36-x86_64  chroot, and start a distgit build for Satyr package, while copr will properly select the distgit repository, the default branch selected is "wrong": COPR will try to build rawhide HEAD instead of f36 HEAD.

Since the committish information is optional, and since the correct repository is selected, I would have assumed that the proper branch is also selected.
Thus, looking at the "import.log" it can be clearly seen that f36 branch is selected in the COPR git, while the source "build-live.log" doesn't select any specific branch (hence the default one is taken). It feels like the logic is available to select the correct branch, but not always used.

If that is the expected behaviour, may you make it more explicit in the UI/documentation ?

Assuming you have multiple chroots in a project, I understand that it may be complicated to have multiple sources simultaneously if the branches diverged.

**Comment by fberat** [comment]
A side effect of that is, if you use COPR as a non-official repository, you must have either multiple project for each needed chroot, or the same spec file for all chroots.

While it may be desirable to have a unique spec file, that may not always be possible. e.g. for a python rpm package, build rules have changed in the past years, and it may not be possible to maintain the same branch for Rawhide and EPEL8 if you want to stick to the latest rules.

**Comment by praiskup** [comment]
I'm not sure why I missed this question, sorry for the late reply.

This is expected behavior.  You even have a way to specify `committish` for "from dist-git" builds, and it sort of implies that all chroots will use the same spec file (related to the same `committish`).

So yes, having an option for "clever chroot->dist-git-branch mapping" would be nice, but expensive for implementation/documentation and with a relatively low gain.  Though patches are welcome.

What users typically do is that they have the same spec file, or they submit multiple builds for
each (different) spec file (== branch/committish), each build with different set of chroots.

**Comment by FrostyX** [comment]
Hello @fberat, do you think you would find this explanation useful? 
PR #2694

**Comment by fberat** [comment]
> Hello @fberat, do you think you would find this explanation useful? PR #2694

Yes, thanks.
