### ISSUE TITLE
Unlimited number of pinned projects per user

### ISSUE THREAD

**Issue by FrostyX** [fedora-copr/copr#2559]
Creating this issue from a #1890 comment:

[pgfed](https://accounts.fedoraproject.org/user/pgfed) commented at 2021-09-24 14:38:05:
asked in #fedora-buildsys to write this up & add as a comment ...

re: pinning

current pinning implementation

(a) is limited to four slots
(b) provides only one 'level', or 'category' of pin
(c) only works for projects that are published to the 'home page'

cref: https://pagure.io/copr/copr/blob/281798717b19ff2163ebf1bc0770a50e9bc9782c/f/frontend/coprs_frontend/coprs/logic/complex_logic.py#_298

lots of people use COPRs as a staging ground for eventual promote-to-fed-pkgs packaging development.
some consider pinning a tool to 'boast' about their ... packages.

those are neither my usage, nor my interest.

I use COPRs to build/maintain what FedPkg'ing doesn't &/or never will, where my primary development/support interest is to the ~1K+ users in my 'space'.
COPR supports that task in making Fedora more easily usable/maintainable here. To that end, tools that make 'me' more efficient at supporting 'them' are useful.

pinning is helpful to organize my COPRs so as not to have to slog through pages of COPR projects that I'm not currently focused on.

i'd like to see options to:

-- define multiple pin categories/tags
-- assign projects to multiple categories/tages
-- pin non-home-page-published projects in MY workspace
-- defined/select pin display ordering in MY workspace

**Comment by xsuchy** [comment]
I close this. It is an industry-standard to allow pinning only a limited number of projects (e.g. see github.com). It follows psychology which says that you can foster only max three big projects. So the pins should highlight these big projects under heavy development.
With this feature, we would eventually get to the priority system and management of cards. Instead of this, I would instead focus on better searchability of projects.
