### ISSUE TITLE
How can i rename a chroot in copr

### ISSUE THREAD

**Issue by pkking** [fedora-copr/copr#2702]
My use case: 
as openEuler have some LTS releases such as openeuler-22.03-LTS-SP1. but in our prod env the name is already setup as openeuler-22.03-x86_64, so wondering how can i change the chroot name safely?

**Comment by praiskup** [comment]
There's no easy way to do this ATM.  We don't rename chroots typically -> we did once "in modern" history,
 and it wasn't an easy change.

The thing is that all the users have local `*.repo` files pointing at the old path on copr-backend.
Therefore we installed symlinks for each chroot occurrence, see the script from 6deba093c11.

The rename was:
```diff
- centos-stream-x86_64
+ centos-stream-8-x86_64 
```

Closing, but feel free to continue the discussion.

**Comment by praiskup** [comment]
@pkking that is a nice summary!  Do you want to wrap it as a `./doc/*maint*`  documentation?
Otherwise, I don't see any question and I don't have any suggestions.  Just that all the steps
are pretty manual (we don't have a magic button implemented, concentrating on naming the
chroots correctly since beginning so the chroot renames are not needed in practice).

**Comment by pkking** [comment]
If our operation works, will try to fill a PR to documents :)
