### ISSUE TITLE
Let's have a new release

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#2708]
Tasks to finish, and things that we shouldn't forget while doing the update:

- [ ] ~~copr-dist-git problems with up2date python3-rpkg, we merged the [ansible PR](https://pagure.io/fedora-infra/ansible/pull-request/1386) and we need to update to python3-rpkg~~
- [x] deallocate the AWS instances we have for the pre-release testing

**Comment by nikromen** [comment]
just posting a comment here to get notification on this issue

**Comment by praiskup** [comment]
> just posting a comment here to get a notification on this issue

There's also the "Subscribe" button in the right panel.  But I tend to follow this project to receive everything anyway...

**Comment by praiskup** [comment]
@pkking fyi, the new python3-copr/copr-cli is not compatible with the old versions of copr-frontend;  namely route `/api_3/build/check-before-build` is missing.

**Comment by praiskup** [comment]
https://pagure.io/fedora-infrastructure/issue/11332

**Comment by FrostyX** [comment]
I needed to temporarily comment-out few tasks from backend playbook. Hopefully it won't cause any issues:

- https://pagure.io/fedora-infra/ansible/c/ccab97a1caea186b2251cfdcbe3115dbe90b2b02?branch=main
- https://pagure.io/fedora-infra/ansible/c/3c008322304fdf48c31af7e07034989b8b37e64c?branch=main

You can find the explanation here: https://pagure.io/fedora-infrastructure/issue/11336

Maybe it will get fixed before our release, in that case, we should uncomment it again. Otherwise, we should keep track of it and uncomment when we can.

**Comment by praiskup** [comment]
https://lists.fedorahosted.org/archives/list/copr-devel@lists.fedorahosted.org/thread/RQ222EM3NBYPTYMOFVBU6ABRXCEOBOQN/

**Comment by praiskup** [comment]
Kept open till we have release notes, and the "usage hashmap" is not yet ready.

**Comment by FrostyX** [comment]
- Release notes: https://docs.pagure.org/copr.copr/release-notes/2023-05-25.html
- Usage treemap: https://pagure.io/fedora-infra/ansible/c/4f509ac48bc67dace0861c5c491930566c25e01a
