### ISSUE TITLE
Build artifacts take extremely long to generate

### ISSUE THREAD

**Issue by Kaz205** [fedora-copr/copr#2940]
Build artifacts appear to take over a day to generate, after the build is completed, for big projects like Firefox. I tried regenerating the repositories, but that didn't help.
https://copr.fedorainfracloud.org/coprs/kaz205/firefox/build/6483932/

**Comment by FrostyX** [comment]
Hello @Kaz205,
thank you for the report.

Taking a look at the build you linked, it took 4 hours to finish. Then it was switched to the succeeded state and by that point, it should be installable via DNF when enabling the Copr project.

By "Build artifacts appear to take over a day to generate" do you mean opening this directory and looking at results?
https://download.copr.fedorainfracloud.org/results/kaz205/firefox/fedora-38-aarch64/06483932-firefox/

That would be probably caused by CDN:
https://docs.pagure.org/copr.copr/user_documentation.html#build-succeeded-but-i-don-t-see-the-built-results

**Comment by Kaz205** [comment]
> That would be probably caused by CDN: https://docs.pagure.org/copr.copr/user_documentation.html#build-succeeded-but-i-don-t-see-the-built-results

Ah I didn't notice that section, that's probably why the artifacts didn't show up in my browser. Thanks for the help!

**Comment by FrostyX** [comment]
No problem, happy to help :-)
