### ISSUE TITLE
UI: Chroot denylist pattern too strict

### ISSUE THREAD

**Issue by sbluhm** [fedora-copr/copr#3012]
When trying to deny a build for ` opensuse-leap-15.5-x86_64`  the message ` Pattern "opensuse-leap-15.5-x86_64" does not match "^[a-z0-9-_*]+$" ` appears and saving is not possible.

Go to Project --> Packages --> <name> --> Section 3 --> Field  `Chroot denylist`.

Enter `opensuse-leap-15.5-x86_64` 

Click save.

Error message appears.

Expectation: This chroot is accepted as it is also available. I guess the ` full stop` is missing from the inclusion list.

**Comment by xsuchy** [comment]
This should be constant defined in some shared module.

**Comment by FrostyX** [comment]
Thank you for the report @sbluhm.

There are two unrelated issues:

1. The chroot denylist input doesn't allow `.` character in the value. That's obviously incorrect and I am fixing it in PR #3055
2. There is currently no `opensuse-leap-15.5-x86_64` chroot in Copr, so until that happens, the value won't be valid. However, after the PR is merged and released, `opensuse-leap-15.4-x86_64` should work because such chroot exists.

**Comment by sbluhm** [comment]
FYI, copr still doesn't show this change. I assume it takes a while for it to be in production.

**Comment by FrostyX** [comment]
That's correct @sbluhm, we do new [Copr releases](https://github.com/fedora-copr/copr/tags) every two or three months.
