### ISSUE TITLE
Upgrade Copr builders to Fedora 39

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#3036]
Fedora 39 is out now, we should move from the current Fedora 38 golden images.

**Comment by nikromen** [comment]
this needs to be done as well - #3053

**Comment by nikromen** [comment]
please skip s390x images for IBM cloud (internal ones)

**Comment by FrostyX** [comment]
Mainly just notes for myself.

- [ ] I wasn't able to get s390x (Fedora Copr) working yet.
- [ ] The `runtest-custom-method.sh` test fails because of

```
INFO: Package manager dnf5 detected and used (direct choice)
Start: installing minimal buildroot with dnf5
execv(/usr/bin/dnf5) failed: No such file or directory
WARNING: DNF5 command failed, retrying, attempt #2, sleeping 10s
execv(/usr/bin/dnf5) failed: No such file or directory
WARNING: DNF5 command failed, retrying, attempt #3, sleeping 10s
execv(/usr/bin/dnf5) failed: No such file or directory
```

I am not yet sure if this is related to the update or not.

- [ ] The `runtest-openmandriva.sh` is still failing because of i686 chroots. Looks like the configs are broken. I will create/ping Mock issue or disable them if they are not supported anymore
- [ ] The `runtest.sh` is failing, I need to figure out why

**Comment by FrostyX** [comment]
> execv(/usr/bin/dnf5) failed: No such file or directory

Maybe this is caused by #3132?

**Comment by praiskup** [comment]
> > execv(/usr/bin/dnf5) failed: No such file or directory
> 
> Maybe this is caused by #3132?

I don't know. Seems like the bootstrap chroot was, for some reason, pregenerated with `config_opts["package_manager"] = 'dnf'` instead of `dnf5`.  Then, there's [the bug](https://bugzilla.redhat.com/show_bug.cgi?id=2263260) and [RFE](https://github.com/rpm-software-management/mock/issues/1289).

**Comment by FrostyX** [comment]
> I don't know. Seems like the bootstrap chroot was, for some reason, pregenerated with config_opts["package_manager"] = 'dnf' instead of dnf5.

That seems to be the case. When I SSH on a builder and check `/etc/mock/templates/fedora-branched.tpl`, there is

```python
config_opts['package_manager'] = 'dnf'
```

We have the following packages there:

```
mock-5.4-1.fc39.noarch
mock-core-configs-39.4-1.fc39.noarch
```
