### ISSUE TITLE
Fedora review have issues in rawhide chroots

### ISSUE THREAD

**Issue by xsuchy** [fedora-copr/copr#3147]
Fedora review have issues in rawhide chroots. This seems to be due dnf3 vs. dnf5

Example: https://download.copr.fedorainfracloud.org/results/@fedora-review/fedora-review-2264719-blesh/fedora-rawhide-x86_64/07030872-blesh/fedora-review/fedora-review.log.gz

This may need a fix on fedora-review side. Filing it here so I do not forget till Monday.

**Comment by FrostyX** [comment]
This will probably be annoying for many people because this likely causes Fedora Review Service to fail for every ticket

**Comment by FrostyX** [comment]
Another example: https://copr.fedorainfracloud.org/coprs/g/fedora-review/fedora-review-2262694-materialx/build/7013260/

**Comment by FrostyX** [comment]
I think I understand what is going on but I didn't have time to fix this yet.

In the logs, we can se

> INFO: Package manager dnf5 detected and used (direct choice)

and 

> INFO: Package manager dnf5 detected and used (fallback)

And no errors, so DNF5 is there and it works fine.

The failure comes from this command

> '['mock', '-r', '/var/lib/copr-rpmbuild/results/configs/child.cfg', '--no-cleanup-after', '--no-clean', '-qn', '--enable-network', 'shell', '--', 'dnf-3 repoquery -C -l filesystem']'

and IMHO not because dnf-3 command wouldn'tbe available but because of the `-C` (cache only) parameter

When reproducing this manually, I get

> [root@builder /]# mock -r fedora-rawhide-x86_64 --no-cleanup-after --no-clean -qn --enable-network shell -- dnf-3 repoquery -C -l filesystem
> Error: Cache-only enabled but no cache for 'fedora'

Well duh, `dnf-3` has no cache, probably only `dnf-5` has. Without the `-C` parameters it is slower but it works fine.

I think the solution might be checking if the cache exists and only in such case adding `-C`.

**Comment by FrostyX** [comment]
Fedora-review upstream issue: https://pagure.io/FedoraReview/issue/511

**Comment by FrostyX** [comment]
PR: https://pagure.io/FedoraReview/pull-request/513
