### ISSUE TITLE
Weird Copr documentation style in Firefox on F40 

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#3275]
![Screenshot_20240521_095437](https://github.com/fedora-copr/copr/assets/3277839/4d18d85b-66e7-4bda-8005-7c50b9457502)

I re-generated the docs yesterday (also on F40), after merging #3269 - so the generator could have changed as well.

**Comment by FrostyX** [comment]
Same in Google Chrome.

When you do `make html` and open the local files in the web browser, is it broken as well? Because mine looks good 

![Screenshot_2024-05-21_11-12-14](https://github.com/fedora-copr/copr/assets/2151771/4caed585-f65e-4d38-be6b-92631afffe64)

So it may have something to do with where the page is build instead of where it is viewed.

**Comment by praiskup** [comment]
yes, works fine with `make html` ... OK, I'm going to re-generate, perhaps that was just a temporary problem when pushing?

**Comment by praiskup** [comment]
doesn't help, the problem seems to be the CSS color specification for **visited** links ... :shrug:

**Comment by FrostyX** [comment]
I can confirm this is caused by building the documentation on F40 (in opposite to viewing the documentation on F40 that we assumed earlier). After I upgraded to F40 it started building the documentation with this glitch. However, only at https://docs.pagure.org/copr.copr while locally it looked fine. The exact same behavior as for @praiskup.

Proposing PR #3310
